### ISSUE TITLE
[Feature request] export methods that work with any kind of data

### ISSUE THREAD

**Issue by jhilden** [claudetech/js-change-object-case#1]
What do you think about exporting a method that you can pass any kind of data (object, array, string, number, ...) and it will automatically determine the right thing to do.

Something like:
```
function camelize (data, options) {
  if (isArray(data)) {
    return camelArray(data, options)
  } else if (isObject(data)) {
    return camelKeys(data, options)
  } else {
    return data
  }
}
```

Would that be something that you would consider adding to the library?

**Comment by tuvistavie** [comment]
Hi, and thanks for proposing.
If you would like to send a PR, I will be glad to merge it.
